@baseUrl = http://localhost:3333


### Get Users by CPF
GET {{ baseUrl }}/account 
cpf: 123
Content-Type: application/json


### Create an account
POST  {{ baseUrl }}/account
Content-Type: application/json

{
    "cpf": "123",
    "name": "jose"
}

### Get statement by CPF
GET {{ baseUrl }}/statement
Content-Type: application/json
cpf: 123

### Get statement by CPF and data
GET {{ baseUrl }}/statement/date?date=2023-08-07
Content-Type: application/json
cpf: 123


### Make a deposit
POST  {{ baseUrl }}/deposit
Content-Type: application/json
cpf: 123

{
    "amount": 100,
    "description": "test"

}


### Make a withdraw
POST  {{ baseUrl }}/withdraw
Content-Type: application/json
cpf: 123
  
  {
      "amount": 100
  
  } 


### update the name of the user
PUT  {{ baseUrl }}/account
Content-Type: application/json
cpf: 123

{
    "name": "jose luiz"
}
 